openapi: 3.1.0
info:
  title: Redmine Users API
  version: 1.0.0
paths:
  /users:
    get:
      summary: ユーザーの一覧を取得
      description: 管理者権限が必要です。
      parameters:
        - in: query
          name: status
          schema:
            type: integer
            enum:
              - 1
              - 2
              - 3
          description: 'ユーザーステータスでフィルタリングします。1: アクティブ, 2: 登録済み, 3: ロック済み'
        - in: query
          name: name
          description: ログイン名、姓名、メールアドレスでフィルタリングします。
          schema:
            type: string
        - in: query
          name: group_id
          schema:
            type: integer
          description: 特定グループに所属するユーザーでフィルタリングします。
        - in: query
          name: limit
          schema:
            type: integer
          description: 取得するユーザーの最大数。
        - in: query
          name: offset
          schema:
            type: integer
          description: 取得するユーザーのオフセット。
      responses:
        '200':
          description: 成功
  post:
    summary: ユーザーを作成
    description: 管理者権限が必要です.
    requestBody:
      required: true
      content:
        application/json:
          schema:
            type: object
            properties:
              user:
                type: object
                properties:
                  login:
                    type: string
                    description: ログイン名
                  password:
                    type: string
                    description: パスワード
                  firstname:
                    type: string
                    description: 名
                  lastname:
                    type: string
                    description: 姓
                  mail:
                    type: string
                    description: メールアドレス
                  auth_source_id:
                    type: integer
                    description: 認証モード ID
                  mail_notification:
                    type: string
                    description: メール通知設定 (only_my_events, none など)
                  must_change_passwd:
                    type: boolean
                    description: パスワード変更が必要かどうか
                  generate_password:
                    type: boolean
                    description: パスワードを自動生成するかどうか
                  custom_fields:
                    type: object
                    description: カスタムフィールド
                required:
                  - login
                  - firstname
                  - lastname
                  - mail
          required: true
    responses:
      '201':
        description: ユーザーが作成されました。
      '422':
        description: バリデーションエラーによりユーザーが作成されませんでした。
  /users/{id}:
    get:
      summary: 特定のユーザーの詳細を取得
      description: |
        `/users/current.:format` で、APIにアクセスするために使用される認証情報を持つユーザーを取得できます。
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ユーザーID
        - in: query
          name: include
          schema:
            type: string
            enum:
              - memberships
              - groups
          description: 'レスポンスに含める関連情報。カンマ区切りで複数指定できます。memberships:
            ユーザーのプロジェクトメンバーシップとロールに関する情報を追加します。groups: ユーザーのグループに関する情報を追加します
            (Redmine 2.1 以降)。'
      responses:
        '200':
          description: 成功
    put:
      summary: ユーザーを更新
      description: 管理者権限が必要です。
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ユーザーID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user:
                  type: object
                  properties:
                    login:
                      type: string
                      description: ログイン名
                    password:
                      type: string
                      description: パスワード
                    firstname:
                      type: string
                      description: 名
                    lastname:
                      type: string
                      description: 姓
                    mail:
                      type: string
                      description: メールアドレス
                    auth_source_id:
                      type: integer
                      description: 認証モード ID
                    mail_notification:
                      type: string
                      description: メール通知設定 (only_my_events, none など)
                    must_change_passwd:
                      type: boolean
                      description: パスワード変更が必要かどうか
                    generate_password:
                      type: boolean
                      description: パスワードを自動生成するかどうか
                    custom_fields:
                      type: object
                      description: カスタムフィールド
                admin:
                  type: boolean
                  description: ユーザーに管理者権限を付与するかどうか
              required: true
      responses:
        '200':
          description: 成功
    delete:
      summary: ユーザーを削除
      description: 管理者権限が必要です。
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ユーザーID
      responses:
        '204':
          description: ユーザーが削除されました。